config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :compras

  resources :circulos do
    post 'add_usuario', to: 'circulos#add_usuario', as: :add_usuario
    delete 'remove_usuario/:usuario_id', to: 'circulos#remove_usuario', as: :remove_usuario
    post 'abandonar', to: 'circulos#abandonar', as: :abandonar
  end

  devise_for :usuarios
  resources :usuarios
  resources :admins, controller: :usuarios
  resources :coordinador, controller: :usuarios

  get 'carts/show'

  resources :productos do
    collection { post 'upload' }
  end
  resources :categorias
  resources :pedidos, only: [:index, :show, :edit]
  resources :home
  resources :steps

  resource :cart, only: [:show] do
    put 'add/:producto_id', to: 'carts#add', as: :add_to
    put 'remove/:producto_id', to: 'carts#remove', as: :remove_from
    put 'create_pedido', to: 'carts#create_pedido', as: :create_pedido
  end

  root to: 'home#index'

end

app/models/pedido.rb
require 'csv'

class Pedido < ActiveRecord::Base
  belongs_to :circulo
  belongs_to :usuario
  belongs_to :ciclo, class_name: "Compra", foreign_key: :compra_id

  validate :circulo, presence: true

  has_paper_trail

  def total
    total = 0.0
    JSON.parse(items).each { |item| total += item['total'] || 0 }
    total.to_f
  end

  def save_in_session(session)
    carrito = Cart.new(session)
    JSON.parse(items, symbolize_names: true).each do |item|
      carrito.add(item[:producto_id], item[:cantidad])
    end
  end

  def self.to_csv
    CSV.generate(force_quotes: true) do |csv|
      csv << ['Pedido Nro', 'Ciclo Nro', 'Usuario Nro', 'Usuario', 'Circulo Nro', 'Codigo Prod.', 'Nombre Prod.', 'Cantidad']
      all.each do |pedido|
        JSON.parse(pedido.items, symbolize_names: true).each do |item|
          begin
            producto = Producto.find(item[:producto_id])
            csv << [
              pedido.id,
              pedido.ciclo.id,
              pedido.usuario.id,
              "#{pedido.usuario.apellido}, #{pedido.usuario.nombre}",
              pedido.circulo.id,
              producto.codigo,
              producto.nombre,
              item[:cantidad]
            ]
          rescue ActiveRecord::RecordNotFound
            csv << [
              pedido.id,
              pedido.ciclo.id,
              pedido.usuario.id,
              "#{pedido.usuario.apellido}, #{pedido.usuario.nombre}",
              pedido.circulo.id,
              item[:producto_id],
              'ERROR',
              item[:cantidad]
            ]
          end
        end
      end
    end
  end

end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit]

  def index
    if current_usuario.admin?
      @pedidos = Pedido.all
      @ciclo_id = nil
      if(params[:ciclo_id])
        @ciclo_id = params[:ciclo_id]
        @pedidos = @pedidos.where(compra_id: params[:ciclo_id])
      end
      @pedidos = @pedidos.order(:updated_at)
      @ciclos = Compra.all.order('fecha_fin_compras DESC')
      respond_to do |format|
        format.html
        format.csv { render csv: @pedidos.to_csv, filename: "#{Time.now.to_i}_pedidos" }
      end
    elsif current_usuario.coordinador? || current_usuario.usuario?
      @pedidos = Pedido.where(usuario_id: current_usuario.id)
    end
  end

  def show
    if current_usuario.admin?
      @pedidos = Pedido.all
      respond_to do |format|
        format.html
        format.xls
      end
    elsif current_usuario.coordinador? || current_usuario.usuario?
      @pedidos = Pedido.where(usuario_id: current_usuario.id)
    end
  end

  def edit
    @pedido.save_in_session(session)
    @pedido.delete
    redirect_to productos_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end
end

app/views/pedidos/index.html.erb
<%- model_class = Pedido -%>
<div class="row">
  <div class="pedidos">
      <h1>Pedidos realizados</h1>

      <% if current_usuario && current_usuario.admin? %>
        <%= link_to "Exportar CSV", pedidos_path(format: "csv", ciclo_id: @ciclo_id), class: "btn btn-success btn-xs" %>
        <%= form_tag pedidos_path, method: :get, class: 'form-inline' do %>
          <h3>Filtros:</h3>
          <div class="form-group">
            <label for="ciclo_id">Ciclo:</label>
            <%= select_tag "ciclo_id",
                  options_from_collection_for_select(@ciclos, "id", "nombre", @ciclo_id),
                  include_blank: true, class: 'form-control input-sm' %>
          </div>
          <%= submit_tag 'Filtrar', class: "btn btn-success btn-xs" %>
        <% end %>
      <% end %>

      <table class='table table-striped' data-search="true">
        <thead>
          <tr>
            <td>Numero</td>
            <td>Fecha</td>
            <td>Ciclo</td>
            <td>Coordinador</td>
            <td>Cìrculo N°</td>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
        <% @pedidos.each do |p| %>
          <tr>
            <td><%= p.id %></td>
            <td><%= l p.created_at %></td>
            <td><%= p.ciclo.nombre %></td>
            <td><%= p.circulo.try('coordinador') ? (p.circulo.coordinador.nombre + ' ' + p.circulo.coordinador.apellido) : 'SIN COORDINADOR' %></td>
            <td><%= p.circulo.id%></td>
            <td>
              <%= link_to('Ver', pedido_path(p), class: 'btn btn-info btn-mini') %>
            </td>
            <td>
              <% if(p.ciclo.id && Compra::ciclo_actual.try(:id) == p.ciclo.id)%>
                <%= link_to('Modificar',
                      edit_pedido_path(p),
                      data: { confirm: 'Luego de modificar el pedido recuerda volver a enviarlo.' },
                      class: 'btn btn-warning btn-mini') %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/pedidos/show.html.erb
<div class="row">
  <div class="pedidos">
    <div class="col-md-8">
      <h2>Detalle de Pedido</h2>
      <h4><%= @pedido.usuario.nombre %> <%= @pedido.usuario.apellido %></h4>
        <p>Círculo N°: <%= @pedido.circulo.id%></p>
    </div>
    <div class="col-md-4">
      <h3 class="text-right"><%= (@pedido.created_at).strftime('%d/%m/%Y')%></h3>
    </div>

    <div class="breadcrumb col-md-12">
       <%= link_to t('.back', :default => t("helpers.links.back")),
                   pedidos_path %>
      <% if can? [:manage], pedidos_path %>
          <span> | </span>
          <li>
            <%= link_to(pedido_path(@pedido, format:'xls')) do %>
                Exportar a Excel
            <% end %>
          </li>
      <% end %>
    </div>

      <table class='table table-striped'>
        <thead>
          <tr>
            <th class="span8">Producto</th>
            <th class="span2 text-right">Cantidad</th>
            <th class="span2 text-right">Importe Total</th>
          </tr>
        </thead>
        <tbody>
        <% total = 0
           qty = 0
        %>
          <% JSON.parse(@pedido.items).each do |i| %>
            <tr>
              <td class="span8"><%= Producto.find(i['producto_id']).nombre %></td>
              <td class="span2 text-right"><%= i['cantidad'].to_i %></td>
              <td class="span2 text-right"><%= number_to_currency(i['total']) %></td>
            </tr>
            <% total = total+i['total']
            qty = qty +i['cantidad'].to_i %>
          <% end %>
        </tbody>
        <tfoot>
            <tr class="info">
              <td class="span8 text-right">Total</td>
              <td class="span2 text-right"><%= qty %></td>
              <td class="span2 text-right"><%= number_to_currency(total) %></td>
            </tr>
        </tfoot>
      </table>
  </div>
</div>

app/views/pedidos/show.xls.erb
<?xml version="1.0" ?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet">
    <Table>
      <% total = 0
         qty = 0
         @pedidos.each do |pedido| %>
      <Row>
        <Cell><Data ss:Type="String"><%=pedido.usuario.nombre + " " + pedido.usuario.apellido %></Data></Cell>
        <Cell><Data ss:Type="String"><%=pedido.created_at %></Data></Cell>
        <Cell><Data ss:Type="String">Fecha: <%=pedido.created_at %></Data></Cell>
        <Cell><Data ss:Type="String">Circulo: <%=pedido.circulo_id %></Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Producto</Data></Cell>
        <Cell><Data ss:Type="String">Cantidad</Data></Cell>
        <Cell><Data ss:Type="String">Importe</Data></Cell>
      </Row>
      <%
        JSON.parse(pedido.items).each do |i|%>
          <Row>
            <Cell><Data ss:Type="String"><%= Producto.find(i['producto_id']).nombre %></Data></Cell>
            <Cell><Data ss:Type="String"><%=i['cantidad'].to_i  %></Data></Cell>
            <Cell><Data ss:Type="Currency"><%=i['total']  %></Data></Cell>
          </Row>
          <% total = total+i['total']
          qty = qty +i['cantidad'].to_i %>
        <% end %>
          <Row>
            <Cell><Data ss:Type="String">Total</Data></Cell>
            <Cell><Data ss:Type="String"><%= qty %></Data></Cell>
            <Cell><Data ss:Type="Currency"><%= number_to_currency(total) %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>