config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :compras

  resources :circulos do
    post 'add_usuario', to: 'circulos#add_usuario', as: :add_usuario
    delete 'remove_usuario/:usuario_id', to: 'circulos#remove_usuario', as: :remove_usuario
    post 'abandonar', to: 'circulos#abandonar', as: :abandonar
  end

  devise_for :usuarios
  resources :usuarios
  resources :admins, controller: :usuarios
  resources :coordinador, controller: :usuarios

  get 'carts/show'

  resources :productos do
    collection { post 'upload' }
  end
  resources :categorias
  resources :pedidos, only: [:index, :show, :edit]
  resources :home
  resources :steps

  resource :cart, only: [:show] do
    put 'add/:producto_id', to: 'carts#add', as: :add_to
    put 'remove/:producto_id', to: 'carts#remove', as: :remove_from
    put 'create_pedido', to: 'carts#create_pedido', as: :create_pedido
  end

  root to: 'home#index'

end

app/models/cart.rb
include ActionView::Helpers::NumberHelper
include ActionView::Helpers::TextHelper

class Cart
  attr_reader :items

  def initialize(session)
    @session = session
    @session[:items] ||= {}
    load!
  end

  def load!
    @items = {}
    @session[:items].each do |producto_id, cantidad|
      @items[producto_id] = Item.new(
                  Producto.find_by_id(producto_id),
                  cantidad
                )
    end
  end

  def empty!
    @session[:items] = {}
    load!
  end

  def empty?
    @session[:items].empty?
  end

  def add(producto_id, cantidad)
    @session[:items][producto_id] = cantidad
    load!
  end

  def remove(producto_id)
    @session[:items].delete(producto_id)
    load!
  end

  def producto?(producto_id)
    @items.key?(producto_id.to_s)
  end

  def cantidad
    total = 0.0
    @items.each do |_k, v|
      Rails.logger.debug(v)
      total += v.cantidad || 0
    end
    total.to_i
  end

  def ahorro
    total_mision = total_ahorro = 0
    @items.each do |_k, v|
      next if v.total == 0 || v.total_super == 0
      total_mision += v.total
      total_ahorro += v.total_super
    end
    return 0 if total_ahorro == 0
    (1 - (total_mision / total_ahorro)).to_f * 100
  end

  def total
    total = 0.0
    @items.each do |_k, v|
      total += v.total || 0
    end
    total.to_f
  end

  def formated_total
    ActionView::Helpers::NumberHelper.number_to_currency(total)
  end

  def formated_cantidad
    pluralize(cantidad, ' producto', ' productos')
  end

  def to_json
    { cantidad: formated_cantidad,
      ahorro: ahorro,
      total: formated_total }.to_json
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # Habilitar cuando se instale devise
  # before_action :authenticate_user!

  # before_action :set_carrito, only: [:show, :add, :remove]

  def show
    @ciclo_actual = Compra::ciclo_actual
  end

  def add
    @carrito.add(params[:producto_id], params[:cantidad])
    render json: @carrito.to_json, status: 200
  end

  def remove
    @carrito.remove(params[:producto_id])
    render json: @carrito.to_json, status: 200
  end

  def create_pedido
    pedido = Pedido.new
    ciclo_id = Compra.ciclo_actual.id
    pedido.items = @carrito.items.map { |_k,item| item.purchase_data }.to_json
    pedido.usuario_id = current_usuario.id
    pedido.circulo_id = current_usuario.circulo_id
    pedido.compra_id = ciclo_id
    respond_to do |format|
      if pedido.save!
        @carrito.empty!
        format.html { redirect_to root_path, notice: 'Pedido enviado a al coordinador' }
      else
        format.html { render :show }
      end
    end
  end

  private

  # # Use callbacks to share common setup or constraints between actions.
  # def set_carrito
  #   @carrito = Cart.new(session)
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.permit(:producto_id, :cantidad)
  end
end

app/views/carts/_menu.html.erb
<style type="text/css">
  body { padding-top: 180px; }
</style>
<div class="carrito">
  <div class="container">
  <ul class="navbar-nav">
      <li class="col-3">Datos de tu compra</li>
      <li class="col-3">Ahorro: <span class="cart-ahorro"><%= number_to_percentage(@carrito.ahorro) %></span></li>
      <li class="col-3">
        <span class="cart-total"><%= number_to_currency(@carrito.total) %></span><br>
        <span class="cart-cantidad"><%= pluralize(@carrito.cantidad, ' producto', ' productos') %></span>
      </li>
      <li class="col-4">
        <% if (controller.controller_name == 'carts') %>
          <%= link_to(productos_path, class: 'prod-list') do %>
            <i class="icon-lmcart"></i>Ir a la Tienda
          <% end %>
        <% else %>
          <%= link_to(cart_path, class: 'prod-list') do %>
            <i class="icon-lmcart"></i>Ver Mi Compra
          <% end %>
        <% end %>
      </li>
  </ul>
  </div>
</div>
<nav class="navbar navbar-default menu-categorias">
  <div class="container-fluid submenu">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Todas', productos_path, class: 'navbar-link' %></li>

        <% @categorias_menu.each do |c| -%>
            <% if c[:subcategorias].present? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= c[:nombre] %> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <% c[:subcategorias].each do |sm| %>
                      <li><%= link_to sm[:nombre], productos_path(categoria_id: c[:id], subcategoria_id: sm[:id])%></li>
                    <% end %>
                  </ul>
                </li>
            <%else %>
                <li><%= link_to c[:nombre], productos_path(categoria_id: c[:id]), class: 'navbar-link' %></li>
            <% end %>
        <% end -%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/carts/show.html.erb
<% content_for :cart_menu do %>
  <%= render 'carts/menu' %>
<% end %>
<div class="mycart">
  <div id="mycart" class="row cart">

      <% if @ciclo_actual && current_usuario && current_usuario.circulo && !current_usuario.pedido?(Compra::ciclo_actual) %>
        <h1 class="titulo">Revisa tu pedido y confirmalo.</h1>

        <p class="explicacion">
          <b>Ciclo Actual: Desde el <%= l @ciclo_actual.fecha_inicio_compras %> hasta el <%= l @ciclo_actual.fecha_fin_compras %></b><br/>
          <b>Ultimo dia para pago:</b> <%= l @ciclo_actual.fecha_fin_pagos %><br/><br/>
          A continuación, un listado con tu pedido. Revisalo, y si está todo bien,<br />
          confirmalo haciendo click en el boton "Finalizar compra".</p>
      <% elsif !@ciclo_actual %>
        <p class="explicacion"><span class="label label-warning">No hay un ciclo de compras activo, en estos momentos no se puede relizar el pedido.</span></p>
      <% elsif current_usuario && !current_usuario.circulo %>
        <p class="explicacion"><span class="label label-warning">No perteneces a ningun circulo. Comunicate con un coordinador. Recuerda que tu numero de usuario es <b><%= current_usuario.id %></b></span></p>
      <% elsif current_usuario && current_usuario.pedido?(Compra::ciclo_actual) %>
        <p class="explicacion"><span class="label label-warning">Disculpa. Ya haz realizado tu pedido. Por el momento la misión solo admite un pedido por usuario por ciclo.</span></p>
      <% elsif current_usuario.nil? %>
        <p class="explicacion"><span class="label label-warning">Disculpa. Para realizar una compra debes ingresar al sitio (previa registracion).</span></p>
      <% end %>
      <div class="span-12 text-right"><%= link_to('Seguir comprando', productos_path) %></div>
      <% unless @carrito.empty? %>

        <table class="table">
          <thead>
            <tr>
              <th>&nbsp;</th>
              <th>Producto</th>
              <th>Código</th>
              <th>Precio Unit.</th>
              <th>Precio Total</th>
              <th>Ahorro Total</th>
              <th>Acción</th>
            </tr>
          </thead>
          <tbody>
          <% @carrito.items.each do |_producto_id, item| %>
            <tr class="cart-item">
              <td><%= item.cantidad.to_i %> x</td>
              <td><%= item.producto.nombre %></td>
              <td><%= item.producto.codigo %></td>
              <td><%= number_to_currency(item.producto.precio) %></td>
              <td><%= number_to_currency(item.total) %></td>
              <td><%= number_to_percentage(item.ahorro) %></td>
              <td>
                <%= button_tag(type: 'button', class: 'btn btn btn-danger btn-xs', data: {
                                                   action: 'remove',
                                                   productId: item.producto.id
                                           }) do %>
                  <i class="">Borrar</i>
                <% end %>
              </td>
            </tr>
          <%end%>
            <tr class="checkout-totales">
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>TOTAL:</td>
              <td><span class="cart-total"><%= number_to_currency(@carrito.total) %></span></td>
              <td><span class="cart-ahorro"><%= number_to_percentage(@carrito.ahorro) %></span></td>
              <td>&nbsp;</td>
            </tr>
          </tbody>
        </table>
        <% if @ciclo_actual && current_usuario && current_usuario.circulo && !current_usuario.pedido?(Compra::ciclo_actual) %>
          <div class="row">
            <%= link_to('Finalizar Compra', create_pedido_cart_path, method: :put, class: 'btn btn-default checkout') %>
          </div>
        <% end %>
      <% else %>
        <h3>No tiene productos agregado a su pedido</h3>
      <% end %>
    </div>
</div>