config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :compras

  resources :circulos do
    post 'add_usuario', to: 'circulos#add_usuario', as: :add_usuario
    delete 'remove_usuario/:usuario_id', to: 'circulos#remove_usuario', as: :remove_usuario
    post 'abandonar', to: 'circulos#abandonar', as: :abandonar
  end

  devise_for :usuarios
  resources :usuarios
  resources :admins, controller: :usuarios
  resources :coordinador, controller: :usuarios

  get 'carts/show'

  resources :productos do
    collection { post 'upload' }
  end
  resources :categorias
  resources :pedidos, only: [:index, :show, :edit]
  resources :home
  resources :steps

  resource :cart, only: [:show] do
    put 'add/:producto_id', to: 'carts#add', as: :add_to
    put 'remove/:producto_id', to: 'carts#remove', as: :remove_from
    put 'create_pedido', to: 'carts#create_pedido', as: :create_pedido
  end

  root to: 'home#index'

end

app/models/usuario.rb
require 'csv'

class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :circulo
  has_many :pedidos

  has_paper_trail

  before_create :set_default_role

  ADMIN = 'Admin'
  COORDINADOR = 'Coordinador'
  USUARIO = 'Usuario'

  def nombre
    super.nil? ? '' : super
  end

  def apellido
    super.nil? ? '' : super
  end

  def nombre_completo
    "#{apellido}, #{nombre}"
  end

  def self.types
    [ADMIN, COORDINADOR, USUARIO]
  end

  def admin?
    type == ADMIN
  end

  def coordinador?
    type == COORDINADOR
  end

  def usuario?
    type == USUARIO
  end

  def pedido?(ciclo_de_compra)
    ciclo_de_compra && self.pedidos.try(:last).try(:ciclo) == ciclo_de_compra
  end

  def pedido_del_ciclo(ciclo_de_compra)
    return nil if ciclo_de_compra.nil?
    pedido = self.pedidos.where(compra_id: ciclo_de_compra.id).first
    return pedido if pedido
    nil
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ['Usuario Nro', 'Apellido y Nombre', 'Email', 'Circulo Nro']
      all.each do |usuario|
        csv << [
          usuario.id,
          "#{usuario.apellido}, #{usuario.nombre}",
          usuario.email,
          usuario.try('circulo').try('id') || "sin circulo"
        ]
      end
    end
  end

  private
  def set_default_role
    self.type ||= Usuario::USUARIO
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
    authorize! :index, @usuarios
    respond_to do |format|
      format.html
      format.csv { render csv: @usuarios.to_csv, filename: "#{Time.now.to_i}_usuarios" }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @ciclo_actual = Compra::ciclo_actual
    @ciclo_actual_completo = Compra::ciclo_actual_completo
  end


  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario creado exitosamente.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario modificado exitosamente..' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      valid_params = [ :nombre, :apellido, :email, :calle, :codigo_postal,
        :ciudad, :pais, :tel1, :cel1, :type, :"fecha_de_nacimiento(1i)",
        :"fecha_de_nacimiento(2i)", :"fecha_de_nacimiento(3i)" ]
      valid_params << :circulo_id if current_usuario && current_usuario.admin?
      filtered_params = params.require(:usuario).permit(valid_params)
    end
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario, as: :usuario, html: { class: 'form-horizontal'}) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> No se pudo guardar el usuario:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :nombre, class: "form-control" %></div>
  </div>
  <div class="form-group">
    <%= f.label :apellido, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :apellido, class: "form-control"  %></div>
  </div>
  <div class="form-group">
    <%= f.label :fecha_de_nacimiento, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.date_select :fecha_de_nacimiento, start_year: 1900 %></div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :email, class: "form-control"  %></div>
  </div>
  <div class="form-group">
    <%= f.label :calle, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :calle, class: "form-control"  %></div>
  </div>
  <div class="form-group">
    <%= f.label :codigo_postal, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :codigo_postal, class: "form-control"  %></div>
  </div>
  <div class="form-group">
    <%= f.label :ciudad, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :ciudad, class: "form-control"  %></div>
  </div>
  <div class="form-group">
    <%= f.label :pais, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :pais, class: "form-control"  %></div>
  </div>
  <div class="form-group">
    <%= f.label :tel1, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :tel1, class: "form-control"  %></div>
  </div>
  <div class="form-group">
    <%= f.label :cel1, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"><%= f.text_field :cel1, class: "form-control"  %></div>
  </div>
  <% if current_usuario && current_usuario.admin? %>
    <div class="form-group">
      <%= f.label :circulo_id, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"><%= f.select(:circulo_id, Circulo.all.map {|c| [ c.id, c.id ] }, class: "form-control") %></div>
    </div>
  <% end %>
  <% if current_usuario && current_usuario.admin? %>
    <div class="form-group">
      <%= f.label :tipo, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"><%= select(:usuario, :type, Usuario.types.collect {|p| [ p, p ] }, {}, { class: "form-control"}) %></div>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Modificar usuario</h1>
<div class="usuarios">
  <div class="breadcrumb">
    <%= link_to 'Mostrar', @usuario %> |
    <%= link_to 'Volver', usuario_path(current_usuario) %>
  </div>
  <%= render 'form' %>

</div>

app/views/usuarios/index.html.erb
<div class="row">
  <h1>Usuarios</h1>

  <%= link_to "Exportar CSV", usuarios_path(format: "csv"), class: "btn btn-success btn-xs" %>

  <div class="usuarios">
    <div class="navbar navs-fixed">
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_usuario_path,
                  :class => 'btn btn-primary' if can? [:manage], Usuario %>
    </div>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Tipo</th>
            <th colspan="2"></th>
          </tr>
        </thead>

      <tbody>
        <% @usuarios.each do |usuario| %>
            <tr>
              <td><%= usuario.id %></td>
              <td><%= usuario.nombre %></td>
              <td><%= usuario.apellido %></td>
              <td><%= usuario.type %></td>
              <td><%= link_to 'Ver', usuario, class: 'btn btn-info btn-mini' %></td>
              <td><%= link_to 'Modificar', edit_usuario_path(usuario), class: 'btn btn-warning btn-mini' %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/usuarios/new.html.erb
<h1>Crear usuario</h1>
<div class="usuarios">
  <div class="breadcrumb">
    <%= link_to 'Atrás', usuarios_path%>
  </div>
  <%= render 'form' %>
</div>

app/views/usuarios/show.html.erb
<div class="row">
  <h1>Usuario: <%= @usuario.nombre %>  <%= @usuario.apellido %></h1>
  <div class="usuarios">
    <div class="breadcrumb">
      <%= link_to 'Modificar', edit_usuario_path(@usuario), class: 'btn btn-primary' %>
    </div>
      <div class="col-md-6">
        <h3>Tus datos:</h3>

        <p>
          <strong>Nombre:</strong>
          <%= @usuario.nombre %>
        </p>

        <p>
          <strong>Apellido:</strong>
          <%= @usuario.apellido %>
        </p>

        <p>
          <strong>Fecha de nacimiento:</strong>
          <%= @usuario.fecha_de_nacimiento %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @usuario.email %>
        </p>

        <p>
          <strong>Dirección:</strong>
          <%= @usuario.calle %>
        </p>

        <p>
          <strong>Codigo postal:</strong>
          <%= @usuario.codigo_postal %>
        </p>

        <p>
          <strong>Ciudad:</strong>
          <%= @usuario.ciudad %>
        </p>

        <p>
          <strong>Pais:</strong>
          <%= @usuario.pais %>
        </p>

        <p>
          <strong>Tel1:</strong>
          <%= @usuario.tel1 %>
        </p>

        <p>
          <strong>Cel1:</strong>
          <%= @usuario.cel1 %>
        </p>

        <p>
          <strong>Tipo:</strong>
          <%= @usuario.type %>
        </p>
      </div>
      <div class="col-md-6">
        <% if @usuario.circulo.nil? %>
          <h3>No perteneces a ningun circulo.</h3>
          <p class="label-warning">Comunicate con un coordinador de círculo para que te agregue. <br/>Recuerda que tú código de
          usuario es el: <b><%= @usuario.id%></b> </p>
        <% else %>
          <h3>Perteneces al Círculo N°: <%=@usuario.circulo_id %> </h3>
            <% if @ciclo_actual_completo %>
                <p class="text-center">Ciclo Actual: <%= @ciclo_actual_completo.nombre %></p>
                <p>Desde el <strong><%= l @ciclo_actual_completo.fecha_inicio_compras %></strong></p>
                <p>hasta el <strong><%= l @ciclo_actual_completo.fecha_fin_compras %></strong></p>
                <p>Ultimo día para realizar el pago <strong><%= l @ciclo_actual_completo.fecha_fin_pagos %></strong></p>
            <% else %>
                <div class="error text-center">No hay Ciclo Activo</div>
            <% end %>
          <h3>Usuarios en tu circulo:</h3>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Tipo</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Nro ident.</th>
                <th>Pedido</th>
                <th>Importe</th>
                <% if can?(:remove_usuario , @usuario.circulo) %><th>Eliminar del circulo</th><% end %>
              </tr>
            </thead>
            <tbody>
              <% @usuario.circulo.usuarios.each do |u| %>
                <tr <%= (u == current_usuario) ? 'class=strong' : '' %> >
                  <td><%= u.type %></td>
                  <td><%= u.nombre %></td>
                  <td><%= u.apellido %></td>
                  <td><%= u.id %></td>
                  <td><%= u.pedido?(Compra::ciclo_actual_completo) ? '<i class="fa fa-check-circle-o" title="Realizado"></i>'.html_safe : '<i class="fa fa-circle-o" title="Pendiente"></i>'.html_safe %></td>
                  <td><%= number_to_currency(u.pedido_del_ciclo(Compra::ciclo_actual_completo).try('total')) %></td>

                    <% if can?(:remove_usuario , @usuario.circulo) && !u.coordinador?%>
                      <td>
                        <%= link_to 'Eliminar', circulo_remove_usuario_path(circulo_id: @usuario.circulo.id, usuario_id: u.id), method: :delete, data: { confirm: 'Esta seguro?' }, class: 'btn btn-danger btn-xs' + (u.pedido?(Compra::ciclo_actual) ? ' disabled' : '') %>
                        </td>
                    <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="text-right csocial"><span>Cuota Social:</span> $<%=Producto.find_by_codigo('CSOCIAL').precio %></div>
          <% if can?(:remove_usuario , @usuario.circulo) %>
            <i>* Solo podras eliminar usuarios sin pedidos realizados.</i><br/>
            <i>** Para abandonar el circulo, comunicate con la mision.</i>
          <% end %>

          <br/><br/>

          <% if !current_usuario.coordinador? %>
            <%= link_to 'Abandonar circulo', circulo_abandonar_path(@usuario.circulo), method: :post, data: { confirm: 'Seguro de abandonar el circulo?' }, class: "btn btn-danger btn-xs" %>
            <br/><br/>
          <% end %>



          <% if can?(:manage , @usuario.circulo) && !@usuario.circulo.completo? %>
            <%= form_tag(circulo_add_usuario_path(@usuario.circulo), method: "post") do %>
              Agregar usuario nro: <input type="text" value="" name="usuario_id" />
              <button type="submit">Agregar</button>
            <% end %>
          <% end %>

          <% if @usuario.circulo.completo? %>
            <h4>Su circulo esta completo.</h4>
          <% end %>

        <% end %>
      </div>
  </div>
</div>