config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :compras

  resources :circulos do
    post 'add_usuario', to: 'circulos#add_usuario', as: :add_usuario
    delete 'remove_usuario/:usuario_id', to: 'circulos#remove_usuario', as: :remove_usuario
    post 'abandonar', to: 'circulos#abandonar', as: :abandonar
  end

  devise_for :usuarios
  resources :usuarios
  resources :admins, controller: :usuarios
  resources :coordinador, controller: :usuarios

  get 'carts/show'

  resources :productos do
    collection { post 'upload' }
  end
  resources :categorias
  resources :pedidos, only: [:index, :show, :edit]
  resources :home
  resources :steps

  resource :cart, only: [:show] do
    put 'add/:producto_id', to: 'carts#add', as: :add_to
    put 'remove/:producto_id', to: 'carts#remove', as: :remove_from
    put 'create_pedido', to: 'carts#create_pedido', as: :create_pedido
  end

  root to: 'home#index'

end

app/views/layouts/_footer.erb
<div id="footer-content col">
  <!--<div class="container">
    <div class="col-4 align-left "> <%= image_tag "giros.png" %></div>
    <div class="col-4 align-center "> <%= image_tag "monteverde.png" %></div>
    <div class="col-4 align-right "><%= image_tag "fcf.png" %>
  </div>-->
  <div id="footer-bar">
    <div class="container">
      <div class="col-8 footer-bar-left ">
        <%= link_to(root_path) do %>
            <span class="icon-house"></span>INICIO
        <% end %>
        <a href="http://misionantiinflacion.com.ar/contacto" title="Contacto"><span class="icon-location"></span>Contacto</a>
        <a href="http://misionantiinflacion.com.ar" title="Contacto"><span class="icon-new"></span>Preg. Frecuentes</a>
        <a href="http://misionantiinflacion.com.ar/admin?action=logout&amp;redirect_to=http%3A%2F%2Fmisionantiinflacion.com.ar%2F&amp;_wpnonce=8e9bff76f8" title="Cerrar Sesión"><span class="icon-lock"></span>Cerrar Sesión</a>
      </div>
      <div class="col-4 footer-bar-right">
        <a href="https://www.facebook.com/misionantiinflacion" target="_blank" class="lm-facebook"><span class="icon-facebook2"></span>Facebook</a>
        <a href="mailto:mision@concejaldecalle.com.ar" class="lm-twitter"><span class="icon-envelope"></span>Email</a>
      </div>
    </div>
  </div>
  <div id="footer-info-home" class="full">
    <div class="container">
      <div class="col-6">
        <!--<p>© 2014 </p>-->
      </div>
    </div>
  </div>
</div>

app/views/layouts/_menu.html.erb
<style type="text/css">
  body { padding-top: 50px; }
</style>
<div class="navbar navs-fixed navbar-fixed-top">
    <div class="row usuario">
      <div class="container">
          <ul class="nav navbar-nav navbar-left">
            <li>
              <%= link_to(root_path) do %>
                <span class="icon-home"></span>INICIO
              <% end %>
            </li>
            <% if can? [:manage], categorias_path %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <i class="fa fa-chevron-down"></i></a>
              <ul class="dropdown-menu" role="menu">
                <% if can? [:manage], circulos_path %>
                  <li>
                    <%= link_to(circulos_path) do %>
                        <span class="icon-cogs"></span>Circulo
                    <% end %>
                  </li>
                <% end %>
                <% if can? [:manage], categorias_path %>
                  <li>
                    <%= link_to(categorias_path) do %>
                      <span class="icon-key2"></span>Categorías
                      <% end %>
                  </li>
                <% end %>
                <% if can? [:manage], compras_path %>
                  <li>
                    <%= link_to(compras_path) do %>
                      <span class="icon-key2"></span>Ciclo
                      <% end %>
                  </li>
                <% end %>
                <% if can? [:manage], suppliers_path %>
                  <li>
                    <%= link_to(suppliers_path) do %>
                      <span class="icon-key2"></span>Proveedores
                      <% end %>
                  </li>
                <% end %>
                <% if can? [:manage], usuarios_path %>
                  <li>
                    <%= link_to(usuarios_path) do %>
                      <span class="icon-key2"></span>Usuarios
                      <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
            <% end %>
            
            <% if usuario_signed_in? %>
              <li>
                <%= link_to(pedidos_path) do %>
                    <span class="icon-stats"></span>Mis Pedidos
                <% end %>
              </li>
            <% end %>

            <li>
              <%= link_to(productos_path) do %>
                  <span class="icon-lmcart"></span>Tienda
              <% end %>
            </li>
            

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if usuario_signed_in? %>
              <li><p class="navbar-text"><%= truncate(current_usuario.email, length: 32) %></p></li>
              <li class="divider"></li>
              <li><%= link_to('Mis Datos', usuario_path(current_usuario))%></li>
              <li class="divider"></li>
              <li><%= link_to('Cerrar Sesion',
                    destroy_usuario_session_path,
                    method: 'delete') %></li>
            <% else %>
              <li><%= link_to('Registrate', new_usuario_registration_path)%></li>
              <li class="divider"></li>
              <li><%= link_to('Inicia Sesion', new_usuario_session_path)%></li>
            <% end %>
          </ul>
      </div>
    </div>
    <%= yield(:cart_menu) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Misión Anti Inflación</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to cart_path do%>
  <i class="fi-shopping-cart"></i>
  Carrito
  (<span class="cart-count"><%=session[:product_ids].count%></span>)
<%end%>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Mision" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<div class="container-fluid">
  
  <% if usuario_signed_in? %>
    <%= render 'layouts/menu' %>
  <% end %>

  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

  </div><!--/row-->
</div> <!-- /container -->
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mision" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= stylesheet_link_tag "application", "https://fonts.googleapis.com/css?family=Fjalla+One" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render 'layouts/menu' %>

    <div class="main container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
    <%= render 'layouts/footer' %>
  </body>
</html>